server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有路由
            allowed-origin-patterns:
              - "http://localhost:[*]"
            allowed-methods: # 允许的HTTP方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"  # 允许的请求头
            allow-credentials: true  # 是否允许携带凭证（如Cookie）
            max-age: 3600        # 预检请求缓存时间（秒）
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/clients/**
          filters:
            - StripPrefix=1
        - id: usr-service
          uri: lb://usr-service
          predicates:
            - Path=/api/admins/**, 
                   /api/advisors/**, 
                   /api/approval-personnel/**, 
                   /api/risk-officers/**
          filters:
            - StripPrefix=1
        - id: portfolio
          uri: lb://portfolio
          predicates:
            - Path=/api/products/**
            - Path=/api/product-items/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1