spring.application.name=advisory-service
server.port=9003
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.datasource.url=jdbc:mysql://localhost:3306/advisory-service?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=020924

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MVC
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Spring Cloud Bus
spring.cloud.bus.enabled=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ?? spring.config.import ??
# ????????
# spring.config.import=configserver:http://localhost:8888

# ??????????????
spring.cloud.config.enabled=false